FROM confluentinc/cp-kafka-connect:7.5.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:14.0.13

RUN ls -l /usr/share/confluent-hub-components/confluentinc-kafka-connect-elasticsearch
